export type DocumentCategory =
  | "civil"
  | "income"
  | "property"
  | "bank"
  | "university"
  | "identity";

export interface DocumentCatalogEntry {
  code: string;
  name: string;
  country: "Tunisia" | "Italy" | "International";
  institution: string;
  category: DocumentCategory;
  requiresYear: boolean;
  translationDefault: boolean;
  apostilleDefault: "verify" | "yes" | "no";
  requiredInfo?: string;
}

export const DOCUMENT_CATALOG: Record<string, DocumentCatalogEntry> = {
  TUN_FAMILY_RECORD: {
    code: "TUN_FAMILY_RECORD",
    name: "Fiche familiale d’état civil",
    country: "Tunisia",
    institution: "Municipalité, arrondissement municipal ou bureau d’état civil",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Doit identifier l’étudiant, le père, la mère, les frères, les sœurs et les autres membres du foyer. Autres appellations acceptées : fiche familiale, livret de famille, copie certifiée conforme du livret de famille.",
  },
  TUN_BIRTH_EXTRACT: {
    code: "TUN_BIRTH_EXTRACT",
    name: "Extrait d’acte de naissance",
    country: "Tunisia",
    institution: "Municipalité, arrondissement municipal ou bureau d’état civil",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_DEATH_EXTRACT: {
    code: "TUN_DEATH_EXTRACT",
    name: "Extrait d’acte de décès",
    country: "Tunisia",
    institution: "Municipalité, arrondissement municipal ou bureau d’état civil",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_MARRIAGE_CERT: {
    code: "TUN_MARRIAGE_CERT",
    name: "Certificat de mariage",
    country: "Tunisia",
    institution: "Municipalité, arrondissement municipal ou bureau d’état civil",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_DIVORCE_JUDGMENT: {
    code: "TUN_DIVORCE_JUDGMENT",
    name: "Jugement de divorce",
    country: "Tunisia",
    institution: "Tribunal ayant rendu la décision",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_NON_APPEAL: {
    code: "TUN_NON_APPEAL",
    name: "Attestation de non-recours",
    country: "Tunisia",
    institution: "Tribunal ayant rendu la décision",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_SEPARATION_JUDGMENT: {
    code: "TUN_SEPARATION_JUDGMENT",
    name: "Jugement de séparation",
    country: "Tunisia",
    institution: "Tribunal ayant rendu la décision",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_GUARDIANSHIP: {
    code: "TUN_GUARDIANSHIP",
    name: "Jugement de tutelle",
    country: "Tunisia",
    institution: "Tribunal compétent",
    category: "civil",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_DECLARED_INCOME: {
    code: "TUN_DECLARED_INCOME",
    name: "Attestation des revenus déclarés",
    country: "Tunisia",
    institution: "Bureau de contrôle des impôts ou Centre régional de contrôle des impôts",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_NON_IMPOSITION: {
    code: "TUN_NON_IMPOSITION",
    name: "Attestation de non-imposition",
    country: "Tunisia",
    institution:
      "Bureau de contrôle des impôts ou Centre régional de contrôle des impôts du domicile",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_SALARY_TAX_WITHHOLDING: {
    code: "TUN_SALARY_TAX_WITHHOLDING",
    name: "Certificat de retenue d’impôt sur le revenu au titre des traitements et salaires",
    country: "Tunisia",
    institution: "Employeur, service des ressources humaines ou service comptabilité",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Doit indiquer le nom du salarié, l’année concernée, le salaire annuel brut, les retenues fiscales, la signature et le cachet de l’employeur.",
  },
  TUN_PENSION_TAX_WITHHOLDING: {
    code: "TUN_PENSION_TAX_WITHHOLDING",
    name: "Certificat de retenue d’impôt sur le revenu au titre des pensions et rentes viagères",
    country: "Tunisia",
    institution: "CNRPS (secteur public) ou CNSS (secteur privé)",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_SALARY_CERTIFICATE: {
    code: "TUN_SALARY_CERTIFICATE",
    name: "Attestation de salaire annuelle indiquant le total brut annuel",
    country: "Tunisia",
    institution: "Employeur, service des ressources humaines ou service comptabilité",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Doit indiquer le nom du salarié, l’année concernée, le salaire annuel brut, les retenues fiscales, la signature et le cachet de l’employeur.",
  },
  TUN_PENSION_BENEFIT: {
    code: "TUN_PENSION_BENEFIT",
    name: "Attestation de bénéfice de pension",
    country: "Tunisia",
    institution: "CNRPS (secteur public) ou CNSS (secteur privé)",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_PENSION_STATEMENT: {
    code: "TUN_PENSION_STATEMENT",
    name: "Relevé annuel de pension",
    country: "Tunisia",
    institution: "CNRPS (secteur public) ou CNSS (secteur privé)",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_RNE_EXTRACT: {
    code: "TUN_RNE_EXTRACT",
    name: "Extrait du Registre National des Entreprises",
    country: "Tunisia",
    institution: "Registre National des Entreprises",
    category: "income",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo: "Extrait RNE récent.",
  },
  TUN_AGRICULTURAL_LAND: {
    code: "TUN_AGRICULTURAL_LAND",
    name: "Documents relatifs aux terrains agricoles",
    country: "Tunisia",
    institution:
      "Bureau de contrôle des impôts, Office National de la Propriété Foncière ou administration détenant l’acte de propriété",
    category: "property",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_UNEMPLOYMENT_CERT: {
    code: "TUN_UNEMPLOYMENT_CERT",
    name: "Attestation officielle de chômage",
    country: "Tunisia",
    institution: "Bureau de l’emploi, si une attestation de chômage existe",
    category: "income",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_SCHOLARSHIP_PROOF: {
    code: "TUN_SCHOLARSHIP_PROOF",
    name: "Justificatif de bourse",
    country: "Tunisia",
    institution: "Organisme attributaire de la bourse",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_FOREIGN_INCOME: {
    code: "TUN_FOREIGN_INCOME",
    name: "Justificatif de revenu étranger",
    country: "International",
    institution: "Administration fiscale ou employeur du pays concerné",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_OTHER_INCOME: {
    code: "TUN_OTHER_INCOME",
    name: "Document officiel correspondant au revenu",
    country: "Tunisia",
    institution: "Administration ou organisme émetteur du revenu",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_PROPERTY_CERTIFICATE: {
    code: "TUN_PROPERTY_CERTIFICATE",
    name: "Certificat de propriété ou de copropriété",
    country: "Tunisia",
    institution:
      "Office National de la Propriété Foncière, direction régionale ou guichet compétent",
    category: "property",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Doit indiquer si possible : identité du propriétaire, type du bien, localisation, superficie en m², pourcentage ou quote-part, numéro du titre foncier, date de situation (31 décembre de chaque année concernée).",
  },
  TUN_NON_PROPERTY_CERTIFICATE: {
    code: "TUN_NON_PROPERTY_CERTIFICATE",
    name: "Certificat de non-propriété immatriculée et inscrite",
    country: "Tunisia",
    institution: "Office National de la Propriété Foncière",
    category: "property",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_UNREGISTERED_DEED: {
    code: "TUN_UNREGISTERED_DEED",
    name: "Acte de propriété d’un bien non immatriculé",
    country: "Tunisia",
    institution: "Notaire ou administration détenant l’acte / contrat d’achat",
    category: "property",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo: "Acte de propriété, contrat d’achat, acte notarié ou certificat administratif prouvant la propriété.",
  },
  TUN_BANK_STATEMENTS: {
    code: "TUN_BANK_STATEMENTS",
    name: "Relevés de compte bancaire de janvier à décembre",
    country: "Tunisia",
    institution: "Agence bancaire du titulaire ou espace client bancaire officiel",
    category: "bank",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_POSTAL_STATEMENTS: {
    code: "TUN_POSTAL_STATEMENTS",
    name: "Relevés de compte postal de janvier à décembre",
    country: "Tunisia",
    institution: "Poste Tunisienne",
    category: "bank",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  TUN_BALANCE_DEC31: {
    code: "TUN_BALANCE_DEC31",
    name: "Attestation de solde au 31 décembre",
    country: "Tunisia",
    institution: "Agence bancaire ou Poste Tunisienne",
    category: "bank",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Doit mentionner le titulaire, le numéro ou référence du compte, la banque, la devise, le solde et la date exacte.",
  },
  TUN_AVERAGE_BALANCE: {
    code: "TUN_AVERAGE_BALANCE",
    name: "Attestation de solde moyen annuel",
    country: "Tunisia",
    institution: "Agence bancaire ou Poste Tunisienne",
    category: "bank",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Demander à la banque l’équivalent de la « giacenza media » italienne (moyenne annuelle du solde). Si impossible : utiliser les relevés complets de janvier à décembre.",
  },
  TUN_ACCOUNT_CLOSURE: {
    code: "TUN_ACCOUNT_CLOSURE",
    name: "Attestation de clôture de compte",
    country: "Tunisia",
    institution: "Agence bancaire ou Poste Tunisienne",
    category: "bank",
    requiresYear: false,
    translationDefault: true,
    apostilleDefault: "verify",
    requiredInfo:
      "Inclure les relevés du 1er janvier à la date de clôture et le solde à la date de clôture.",
  },
  TUN_SIBLING_STUDENT_PROOF: {
    code: "TUN_SIBLING_STUDENT_PROOF",
    name: "Attestation de scolarité",
    country: "Tunisia",
    institution: "Établissement scolaire ou universitaire",
    category: "income",
    requiresYear: true,
    translationDefault: true,
    apostilleDefault: "verify",
  },
  DOC_PASSPORT: {
    code: "DOC_PASSPORT",
    name: "Passeport",
    country: "International",
    institution: "Document personnel de l’étudiant",
    category: "identity",
    requiresYear: false,
    translationDefault: false,
    apostilleDefault: "no",
  },
  DOC_CODICE_FISCALE: {
    code: "DOC_CODICE_FISCALE",
    name: "Codice fiscale",
    country: "Italy",
    institution: "Agenzia delle Entrate / Universitaly",
    category: "identity",
    requiresYear: false,
    translationDefault: false,
    apostilleDefault: "no",
  },
  DOC_ADMISSION_LETTER: {
    code: "DOC_ADMISSION_LETTER",
    name: "Lettre d’admission ou de préadmission",
    country: "Italy",
    institution: "Université italienne",
    category: "university",
    requiresYear: false,
    translationDefault: false,
    apostilleDefault: "no",
  },
};
